upstream backend {
    server api:8000;
}
upstream frontend {
    server web:3000;
}
server {

    listen 80;
    listen [::]:80;
    server_name localhost;

    # location / {
    #     root /usr/share/nginx/html;
    #     index index.html index.html;
    #     try_files $uri /index.html;
    # }
    proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;

    location / {
        proxy_pass http://frontend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
    }

    location /_next/webpack-hmr {
    proxy_pass http://frontend/_next/webpack-hmr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade"; 
} 

    location /api/ {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
    }

    location /ws/ {
        proxy_pass http://backend;  # Chuyển tiếp đến backend FastAPI
        proxy_http_version 1.1;     # Sử dụng HTTP/1.1 cho WebSocket
        proxy_set_header Upgrade $http_upgrade;  # Thiết lập header Upgrade
        proxy_set_header Connection "upgrade";    # Thiết lập header Connection
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
        proxy_redirect off;
    }

    location /static/ {
        alias /home/app/api/static/;
    }
    location /media/ {
        alias /home/app/api/media/;
    }

}